"""Reusable Pycaso 2-cent coin reconstruction for BA variants.

The companion paper relies on a dense stereo reconstruction of the Pycaso
2-cent coin specimen (DIS optical flow + skew-line triangulation) to
illustrate the practical effect of each calibration hypothesis. This
module factors the triangulation step so it can be called on **any**
26-parameter CMO + per-arm SE(3) vector — typically the rayfield
initialisation, the unregularised BA result, and (later) each
Schur-regularised variant — without rerunning the optical flow.

The reference correspondences and the Zernike-rayfield baseline reconstruction
are read from ``docs/assets/pycaso_real_data/`` (committed checkpoints):

- ``specimen_correspondences.npz``: ``(uL, vL, uR, vR)`` pixel pairs +
  image size + ROI window;
- ``specimen_reconstruction_zernike.npz``: the rayfield Zernike
  reconstruction generated by ``examples/notebooks/10_pycaso_specimen_reconstruction.py``.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np
from scipy.spatial.transform import Rotation

from stereocomplex.optical_ba.residuals import N_TEL
from stereocomplex.physics.cmo_physical import CMOTelecentricStereoModel


@dataclass(frozen=True)
class SpecimenReconstruction:
    """One dense reconstruction of the Pycaso coin specimen.

    Attributes
    ----------
    X, Y, Z : ndarray, shape (N,)
        Triangulated point coordinates in millimetres, one per pixel pair
        deemed valid. Length matches ``valid.sum()`` of the underlying
        correspondences mask.
    gap_mm : ndarray, shape (N,)
        Closest-approach distance between the two back-projected rays of
        each pixel pair; a small gap means the model explains the
        correspondence as a single 3D point.
    valid_mask : ndarray of bool, shape (n_correspondences,)
        Per-correspondence triangulation-validity mask. ``X/Y/Z/gap_mm``
        hold the values at ``valid_mask == True`` only, in the same order;
        keeping the mask lets callers project the cloud back into the
        source ROI image grid.
    image_extent_xy_mm : tuple of (float, float)
        Bounding-box width and height of the valid XY footprint, used as a
        magnification proxy (the physical coin diameter is known: 18.75 mm
        for the 2-cent euro coin).
    median_z_mm : float
        Median Z coordinate (working-distance proxy).
    z_mad_mm : float
        Median absolute deviation of Z; a roughness proxy for the
        reconstructed surface.
    median_gap_mm : float
        Median ray gap.
    variant : str
        Human-readable label of the optical model that produced this cloud.
    """

    X: np.ndarray
    Y: np.ndarray
    Z: np.ndarray
    gap_mm: np.ndarray
    valid_mask: np.ndarray
    image_extent_xy_mm: tuple[float, float]
    median_z_mm: float
    z_mad_mm: float
    median_gap_mm: float
    variant: str


def _triangulate_skew_lines(
    O1: np.ndarray, d1: np.ndarray, O2: np.ndarray, d2: np.ndarray
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Closest-point triangulation of two batches of skew lines.

    Returns the midpoint between the two closest approach points, the gap
    (distance between them), and a validity mask. Numerically degenerate
    pairs (parallel rays) are marked invalid.
    """
    n = np.cross(d1, d2, axis=1)
    n_norm = np.linalg.norm(n, axis=1)
    valid = n_norm > 1e-12

    w = O2 - O1
    cross_d2_n = np.cross(d2, n, axis=1)
    cross_d1_n = np.cross(d1, n, axis=1)

    # Guard the division for the invalid rows; they will be discarded anyway.
    denom = np.where(valid, n_norm**2, 1.0)
    t1 = np.sum(w * cross_d2_n, axis=1) / denom
    t2 = np.sum(w * cross_d1_n, axis=1) / denom

    P1 = O1 + t1[:, None] * d1
    P2 = O2 + t2[:, None] * d2
    midpoint = (P1 + P2) / 2.0
    gap = np.linalg.norm(P1 - P2, axis=1)
    return midpoint, gap, valid


def _apply_se3(O: np.ndarray, d: np.ndarray, rv: np.ndarray, t: np.ndarray) -> tuple[np.ndarray, np.ndarray]:  # noqa: E741
    R = Rotation.from_rotvec(rv).as_matrix()
    return (R @ O.T).T + t[None, :], (R @ d.T).T


def reconstruct_with_cmo_se3(
    theta_26p: np.ndarray,
    *,
    correspondences_path: Path | str,
    pixel_pitch_mm: float = 0.0055,
    variant: str = "cmo_26p",
) -> SpecimenReconstruction:
    """Triangulate the coin correspondences through a CMO + per-arm SE(3) model.

    Parameters
    ----------
    theta_26p : ndarray, shape (26,)
        Optical parameter vector — 14 telecentric CMO entries followed by
        the 12 per-arm SE(3) entries, as in
        :mod:`stereocomplex.optical_ba.residuals`.
    correspondences_path : Path or str
        Path to ``specimen_correspondences.npz`` (uL/vL/uR/vR + image_size).
    pixel_pitch_mm : float
        Sensor pixel pitch (default: Pycaso sensor, 0.0055 mm).
    variant : str
        Label to attach to the result for plotting / aggregation.

    Returns
    -------
    SpecimenReconstruction
        Dense 3-D cloud filtered to valid triangulations plus aggregate
        metrics (XY footprint, median Z, Z MAD, median ray gap).
    """
    theta_26p = np.asarray(theta_26p, dtype=np.float64).reshape(-1)
    if theta_26p.size != N_TEL + 12:
        raise ValueError(f"theta_26p must have {N_TEL + 12} entries, got {theta_26p.size}")

    data = np.load(Path(correspondences_path))
    uL = np.asarray(data["uL"], dtype=np.float64)
    vL = np.asarray(data["vL"], dtype=np.float64)
    uR = np.asarray(data["uR"], dtype=np.float64)
    vR = np.asarray(data["vR"], dtype=np.float64)
    image_size = tuple(int(x) for x in data["image_size"])

    m_tel = CMOTelecentricStereoModel.from_parameter_vector(
        theta_26p[:N_TEL], pixel_pitch_mm=pixel_pitch_mm, image_size=image_size
    )
    rv_L, t_L = theta_26p[14:17], theta_26p[17:20]
    rv_R, t_R = theta_26p[20:23], theta_26p[23:26]

    OL_raw, dL_raw = m_tel.ray(uL, vL, "left")
    OR_raw, dR_raw = m_tel.ray(uR, vR, "right")
    OL, dL = _apply_se3(OL_raw, dL_raw, rv_L, t_L)  # noqa: E741
    OR, dR = _apply_se3(OR_raw, dR_raw, rv_R, t_R)  # noqa: E741

    P, gap, valid = _triangulate_skew_lines(OL, dL, OR, dR)
    return _summarise(P, gap, valid, variant)


def load_zernike_baseline(npz_path: Path | str) -> SpecimenReconstruction:
    """Wrap an existing ``specimen_reconstruction_zernike.npz`` as a result.

    The Zernike-rayfield reconstruction is the published reference; it is
    pre-computed by ``examples/notebooks/10_pycaso_specimen_reconstruction.py``.
    Loading it here avoids re-implementing the Zernike triangulation just to
    show it side-by-side with the CMO variants.
    """
    data = np.load(Path(npz_path))
    X = np.asarray(data["X"], dtype=np.float64)
    Y = np.asarray(data["Y"], dtype=np.float64)
    Z = np.asarray(data["Z"], dtype=np.float64)
    gap = np.asarray(data["gap"], dtype=np.float64)
    valid = np.asarray(data["valid"], dtype=bool)
    P = np.column_stack([X, Y, Z])
    return _summarise(P, gap, valid, variant="zernike_rayfield_57p")


def _summarise(
    P: np.ndarray, gap: np.ndarray, valid: np.ndarray, variant: str
) -> SpecimenReconstruction:
    Xv = P[valid, 0]
    Yv = P[valid, 1]
    Zv = P[valid, 2]
    gv = gap[valid]
    extent = (float(Xv.max() - Xv.min()), float(Yv.max() - Yv.min()))
    median_z = float(np.median(Zv))
    z_mad = float(np.median(np.abs(Zv - median_z)))
    return SpecimenReconstruction(
        X=Xv, Y=Yv, Z=Zv, gap_mm=gv,
        valid_mask=np.asarray(valid, dtype=bool),
        image_extent_xy_mm=extent,
        median_z_mm=median_z,
        z_mad_mm=z_mad,
        median_gap_mm=float(np.median(gv)),
        variant=variant,
    )


# Known physical reference for the magnification check.
EUR_2_CENT_DIAMETER_MM = 18.75


def magnification_ratio(recon: SpecimenReconstruction,
                        nominal_diameter_mm: float = EUR_2_CENT_DIAMETER_MM) -> float:
    """Return the reconstructed-vs-nominal magnification ratio of the XY footprint.

    The coin's XY extent is taken as ``max(width, height)`` from the bounding
    box — coarse but robust to crop rotation. A ratio of 1.0 means the
    reconstruction matches the physical 18.75 mm 2-cent euro diameter; a
    ratio below 1.0 means the model under-magnifies the world.
    """
    w, h = recon.image_extent_xy_mm
    return max(w, h) / float(nominal_diameter_mm)
